services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: donein5_backend
      POSTGRES_PASSWORD: "Wf0jzue56UmBEyJsejA72pi0NVQka19Y"
    volumes:
      - donein5_backend_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "35z7UXF3ouXb5NTBhDmAluPiBZJaotMj"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: donein5_backend_test
      POSTGRES_PASSWORD: "ulsLAUQd7dx30DtYCl-_7Z0Ri-yWywZs"
    volumes:
      - donein5_backend_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "041hjMJoROYpQZaVaFFnrxTNO6KJkSvN"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  donein5_backend_data:
  donein5_backend_test_data:
